apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: demo-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
